application/urls.py
import debug_toolbar
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.urls.conf import re_path

from application import settings

urlpatterns = [
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('authenticator.urls')),
    path('', include('store.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
    path('', include('consultation.urls')),
    path('', include('userprofile.urls')),
    path('', include('waitinglist.urls')),
    path('', include('pay.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

# handler404 = 'store.views.custom_404'

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

    urlpatterns += staticfiles_urlpatterns()

cart/urls.py
from django.urls import path
from .views import add_to_cart, delete_cart, CartView


urlpatterns = [
    path('products/detail/<slug:slug>/add-to-cart/', add_to_cart, name='add-to-cart'),
    path('products/detail/<slug:slug>/delete-item-cart/', delete_cart, name='delete-cart'),
    path('cart/', CartView.as_view(), name='cart'),
]

order/urls.py
from django.urls import path
from .views import OrderView, SuccessOrderView, removeOrder
from authenticator.decorators import check_recaptcha


urlpatterns = [
    path('checkout/', check_recaptcha(OrderView.as_view()), name='checkout'),
    path('checkout/success/', SuccessOrderView.as_view(), name='success-order'),
    path('checkout/delete/<id>/', removeOrder, name='checkout-delete'),
]

pay/urls.py
from django.urls import path
from .views import PaymentView


urlpatterns = [
    path('checkout/payment/<id>/', PaymentView.as_view(), name='payment'),
]

order/models.py
import uuid
import random

from django.core.checks import messages

from application import settings
from cart.models import Cart, ItemCart
from django.apps import apps
from django.core.mail import get_connection, send_mail
from django.db import models
from django.utils.safestring import mark_safe
from store.models import Customer


def random_key_order():
    return str(random.randint(1000000000, 9999999999))


class Order(models.Model):
    STATUS_NEW_ORDER = 'new_order'
    STATUS_PROGRESS_ORDER = 'assembly'
    STATUS_WAIT_BUY_ORDER = 'wait_buy'
    STATUS_READY_ISSUE_ORDER = 'ready'
    STATUS_ISSUED_ORDER = 'issued'
    STATUS_CANCELED_ORDER = 'canceled'

    STATUS_ORDER_CHOICES = (
        (STATUS_NEW_ORDER, 'Новый заказ'),
        (STATUS_WAIT_BUY_ORDER, 'В ожидании оплаты'),
        (STATUS_PROGRESS_ORDER, 'В процессе сборки'),
        (STATUS_READY_ISSUE_ORDER, 'Готов к выдачи'),
        (STATUS_ISSUED_ORDER, 'Выдан'),
        (STATUS_CANCELED_ORDER, 'Отменён'),
    )

    TYPE_PICKUP_DELIVERY = 'pickup'
    TYPE_DELIVERY_DELIVERY = 'delivery'

    TYPE_DELIVERY_CHOICES = (
        (TYPE_PICKUP_DELIVERY, 'Самовывоз'),
        (TYPE_DELIVERY_DELIVERY, 'Доставка'),
    )

    TYPE_CARD_PAYMENT = 'card'
    TYPE_CASH_PAYMENT = 'cash'

    TYPE_BUY_CHOICES = (
        (TYPE_CARD_PAYMENT, 'Оплата картой - онлайн'),
        (TYPE_CASH_PAYMENT, 'Оплата наличными'),
    )

    id = models.SlugField(default=uuid.uuid4, editable=False,
                          primary_key=True, unique=True)
    key = models.CharField(max_length=10, verbose_name='Код заказа',
                           default=random_key_order, unique=True)
    is_confirm = models.BooleanField(verbose_name='Подтвержден', default=False)
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, verbose_name=u'Корзина', related_name='order')
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, verbose_name='Покупатель', related_name='order')
    date = models.DateTimeField(
        auto_now_add=True, verbose_name=u'Дата создания заказа')
    date_of_reg = models.DateTimeField(verbose_name=u'Дата оформления заказа',
                                       null=True, blank=True
                                       )
    amount = models.FloatField(verbose_name=u'Цена', default=0)
    status = models.CharField(default=STATUS_NEW_ORDER,
                              choices=STATUS_ORDER_CHOICES, verbose_name=u'Статус заказа', max_length=255, null=True, blank=True)
    buy = models.CharField(choices=TYPE_BUY_CHOICES,
                           verbose_name=u'Вид оплаты', max_length=255, null=True, blank=True)
    type_delivery = models.CharField(
        choices=TYPE_DELIVERY_CHOICES, verbose_name=u'Вид доставки', max_length=255, null=True, blank=True)
    comment = models.TextField(
        verbose_name=u'Комментарий', null=True, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.id, self.customer.user.username)

    @property
    def comment_safe(self):
        return mark_safe(self.comment)
    comment_safe.fget.short_description = 'Комментарий'

    def save(self, *args, **kwargs):
        DocumentProductQuantity = apps.get_model(
            'documents', 'DocumentProductQuantity')
        if self.status in self.STATUS_PROGRESS_ORDER:
            connection = get_connection(
                host=settings.EMAIL_HOST,
                port=settings.EMAIL_PORT,
                username=settings.EMAIL_HOST_USER,
                password=settings.EMAIL_HOST_PASSWORD,
                use_ssl=settings.EMAIL_USE_SSL
            )
            message = f'''
                {self.customer.user.first_name} {self.customer.user.last_name} здравствуйте!\n
                Был оформлен новый заказ №{self.key}\n
                На сумму {self.amount}\n
                Следите за статусом заказа на сайте
            '''
            send_mail(
                subject=f'Был оформлен новый заказ №{self.key}',
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.customer.user.email],
                fail_silently=False
            )
        if self.status and not self.status in self.STATUS_NEW_ORDER:
            connection = get_connection(
                host=settings.EMAIL_HOST,
                port=settings.EMAIL_PORT,
                username=settings.EMAIL_HOST_USER,
                password=settings.EMAIL_HOST_PASSWORD,
                use_ssl=settings.EMAIL_USE_SSL
            )
            message = f'''
                Уважаемый {self.customer.user.first_name} {self.customer.user.last_name}, 
                ваш заказ №{self.key} сменил статус на: {self.get_status_display()}
            '''
            send_mail(
                subject='Смена статуса заказа',
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.customer.user.email],
                fail_silently=False
            )
        if self.status == self.STATUS_PROGRESS_ORDER:
            cart = Cart.objects.get(id=self.cart_id)
            items = ItemCart.objects.get_items(cart)
            for item in items:
                DocumentProductQuantity.objects.create(
                    product=item.product,
                    quantity=item.quantity,
                    price=item.total_price_discount,
                    type=DocumentProductQuantity.SPENDING_CHOICES
                )
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


# def confirm_key():
#     return str(random.randint(100000, 999999))


# class OrderConfirmed(models.Model):
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     key = models.CharField(max_length=8, default=confirm_key())

products/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from decimal import Decimal
from django.db import models
from django.db.models.fields import DecimalField
from django.db.utils import cached_property
from django.template.defaultfilters import slugify
from mptt.models import TreeForeignKey
from store.managers import ProductManager
from store.models import Brand, Category
from django.db.models import Value, IntegerField
from django.db.models.functions import Coalesce
from unidecode import unidecode
from django.apps import apps
from django.db.models.aggregates import Avg, Sum
from django.db.models.expressions import ExpressionWrapper, OuterRef
from django.db.models.query import F, Q


class Product(models.Model):
    UNDER_THE_ORDER = 'Под заказ'
    IN_THE_SHOP = 'В магазине'

    CHOICES = (
        (UNDER_THE_ORDER, 'Под заказ (14 дней)'),
        (IN_THE_SHOP, 'Покупка в магазине')
    )

    id = models.AutoField(primary_key=True)
    slug = models.SlugField(verbose_name=u'Семантический URL',
                            max_length=150, unique=True)
    model = models.CharField(verbose_name=u'Модель', max_length=50)
    article = models.CharField(
        verbose_name=u'Артикул',
        max_length=35,
        unique=True)
    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        verbose_name=u'Производитель')
    category = TreeForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name=u'Категория')
    description = models.TextField(
        verbose_name=u'Описание',
        max_length=3500,
        blank=True,
        null=True)
    active = models.BooleanField(verbose_name=u'Отображать', default=True)

    type_buy = models.CharField(verbose_name=u'Вид покупки',
                                choices=CHOICES, max_length=255)
    delivery = models.BooleanField(
        verbose_name=u'Доставка', default=False)

    objects = ProductManager()

    def __str__(self):
        return '{0} - {1}'.format(self.article, self.model)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def save(self, *args, **kwargs):
        if not self.slug:
            raw_slug = '%s %s %s' % (self.brand.name, self.model, self.article)
            self.slug = slugify(unidecode(raw_slug))
        return super().save(*args, **kwargs)

    @cached_property
    def rating(self):
        obj = ProductUserAction.objects.filter(
            product=self).aggregate(Avg('rate'))['rate__avg']
        if not obj:
            obj = 0
        rate = '%.2f' % obj
        return rate
    rating.short_description = 'Оценка'

    @cached_property
    def actual_price_with_discount_for_admin(self):
        price = self.actual_price_for_admin
        obj = Product.objects.filter(id=self.id).prefetch_related(
            'discount').aggregate(
                discount=Coalesce(
                    Sum('discount__amount_discount', filter=Q(
                        discount__amount_discount__gt=0, discount__is_active=True)),
                    Value(0)
                )
        )
        price = price - (price * obj['discount']) / Decimal(100)
        return Decimal(price)
    actual_price_with_discount_for_admin.short_description = 'Стоимость с учётом скидок'

    @cached_property
    def actual_quantity_for_admin(self):
        obj = self.get_actual_quantity
        return obj['total_quantity']
    actual_quantity_for_admin.short_description = 'Количесто товаров'

    @cached_property
    def actual_price_for_admin(self):
        DocumentProductPrice = apps.get_model(
            'documents', 'DocumentProductPrice')
        obj = DocumentProductPrice.objects.filter(
            product=self).order_by(
            '-actual_date').values('price')[:1].get()
        return obj['price']
    actual_price_for_admin.short_description = 'Стоимость товара'

    @cached_property
    def get_actual_quantity(self):
        DocumentProductQuantity = apps.get_model(
            'documents', 'DocumentProductQuantity')
        minus = Coalesce(
            Sum('quantity', filter=Q(type=DocumentProductQuantity.SPENDING_CHOICES)),
            Value(0)
        )
        plus = Coalesce(
            Sum('quantity', filter=Q(type=DocumentProductQuantity.COMING_CHOICES)),
            Value(0)
        )
        obj = DocumentProductQuantity.objects.filter(
            product=self
        ).all().values('product').aggregate(
            plus=plus,
            minus=minus,
            total_quantity=plus-minus
        )
        return obj
    get_actual_quantity.short_description = 'Количество'


class Photo(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(
        verbose_name=u'Картинка',
        upload_to='uploads/products/%y/%m/%d/')
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name=u'Продукт',
        related_name='images')

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'


class ProductCharacteristic(models.Model):
    CHOICES = [
        ('Кг', 'Кг'),
        ('Вт', 'Вт'),
        ('кВт', 'кВт'),
        ('Шт', 'Шт'),
        ('См', 'См'),
        ('М', 'М'),
        ('мм', 'мм'),
        ('м2', 'м2'),
        ('Л', 'Л'),
        ('км\ч', 'км\ч'),
    ]

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='characteristic')
    # product = models.ManyToManyField(Product, related_name='characteristic', verbose_name=u'Продукт')
    name = models.CharField(
        max_length=100, verbose_name=u'Характеристика', blank=True, null=True)
    decimal_value = models.DecimalField(
        max_digits=19, decimal_places=10, verbose_name=u'Числовое значение', blank=True, null=True)
    text_value = models.CharField(
        max_length=100, verbose_name=u'Текстовое значение', blank=True, null=True)
    unit = models.CharField(choices=CHOICES, blank=True,
                            null=True, max_length=255)

    def __str__(self):
        return '{0} - {1}'.format(self.product.slug, self.name)

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товаров'


class ProductUserAction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='action', verbose_name=u'Пользователь')
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE, related_name='action', verbose_name=u'Продукт')
    rate = models.PositiveIntegerField(verbose_name=u'Оценка', default=0)
    favorite = models.BooleanField(
        verbose_name=u'Понравившийся', default=False)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.product)

    class Meta:
        verbose_name = 'Отношение Пользователь - Продукт'
        verbose_name_plural = 'Отношения Пользователь - Продукт'


class Discount(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование скидки')
    products = models.ManyToManyField(Product, related_name='discount',
                                      verbose_name=u'Продукты на которые распространяется скидка')
    amount_discount = models.IntegerField(verbose_name=u'Размер скидки в %', validators=[
                                          MaxValueValidator(100), MinValueValidator(0)])
    is_active = models.BooleanField(verbose_name=u'Активность', default=True)
    date_start = models.DateTimeField(
        auto_now_add=True, verbose_name=u'Дата начала действия скидки')
    date_finish = models.DateTimeField(
        verbose_name=u'Дата окончания действия скидки'
    )

    def __str__(self):
        return str(self.amount_discount)

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, related_name='comment', verbose_name=u'Автор')
    body = models.TextField(verbose_name=u'Комментарий')
    date = models.DateTimeField(
        auto_now_add=True, verbose_name=u'Дата создания')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='comment', verbose_name=u'Продукт')

    def __str__(self):
        return self.body

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-date']

blog/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import News, Service


class NewsOverrideAdminForm(forms.ModelForm):
    body = forms.CharField(
        widget=CKEditorUploadingWidget(config_name='default'))

    class Meta:
        model = News
        fields = '__all__'


class ServiceOverrideAdminForm(forms.ModelForm):
    body = forms.CharField(
        widget=CKEditorUploadingWidget(config_name='default')
    )

    class Meta:
        model = Service
        fields = '__all__'

blog/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/breadcrumbs.html
<ol class="breadcrumb m-0">
    {% load i18n %}
    <li class="breadcrumb-item">
        <a href="{% url 'home'%}">{% trans 'Home'%}</a>
    </li>
    
</ol>

frontend/templates/list-product.html
<div class="row w-100">
    <h1>Каталог</h1>
</div>
{% for i in object_list %}
{% load static %}
<div class="col-lg-4 col-md-6 mb-4 wow animated animate__fadeInUp" data-wow-duration="1s" data-wow-delay="0"
    data-wow-offset="5" data-wow-iteration="1">
    <div class="card h-100">
        <div class="position-relative">
            <form action="{% url 'product-add-favorite' i.slug %}" method="POST" class="position-absolute link-like-product">
                {% csrf_token %}
                <button type="submit" class="btn btn-link">
                    <i class="fa fa-heart like-product"></i>
                </button>
            </form>
            <div class="single-item">
                {% for img in i.images.all %}
                <div>
                    <img class=""
                        style="height: 150px; width: 100%; object-fit: contain; cursor: pointer; user-select: none;"
                        src="{{ img.image.url }}" alt="">
                </div>
                {% empty %}
                
                <img src="{% static 'style\img\images\placeholder.png' %}" alt="" style="height: 130px; object-fit: contain;">
                {% endfor %}
            </div>
        </div>
        <div class="card-body">
            {% if i.quantity <= 0 %}
                <i class="fa fa-times" style="color: red;"></i>
                <u>Нет в наличии</u>
            {% else %}
                <i class="fa fa-check" style="color: green;"></i>
                <u>В наличии</u>
            {% endif %}
            <br>
            <small class="m-0">Покупка: {{ i.get_type_buy_display|lower }}</small>
            <small>
                Категория:
                {{ i.category.name }}
            </small>
            <h4 class="card-title">
                <a href="{% url 'detail-product' i.slug %}">{{ i.brand.name }} {{ i.model|truncatewords:"4" }}</a>
            </h4>
            {% if i.discount_sum %}
                <h5>
                    <del>
                        {{ i.price_doc|floatformat:-2 }}&nbsp;&#8381;
                    </del>
                    <span style="color: red;" class="ml-1">
                        {{ i.price_discount|floatformat:-2 }}&nbsp;&#8381;
                    </span>
                </h5>
            {% else %}
                <h5>{{ i.price_discount|floatformat:-2 }}&nbsp;&#8381;</h5>
            {% endif %}
            
            <div class="card-desc">
                <ul class="list-unstyled pl-2">
                    {% for c in i.characteristic.all %}
                        {% if forloop.counter <= 2 %}
                            <li>
                                {{ c.name }}: 
                                {{ c.text_value|default:"" }} 
                                {{ c.decimal_value|default:""|floatformat:1 }} 
                                {{ c.get_unit_display|default:"" }}
                            </li>
                        {% elif forloop.counter == 3 %}
                            <li>...</li>
                        {% else %}

                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'detail-product' i.slug %}" class="btn btn-info">
                Подробнее...
            </a>
        </div>
        <div class="card-footer">
            <small class="text-muted" style="font-size: 18px;">
                {% if i.avg >= 1 %}
                    ★
                {% else %}
                    ☆
                {% endif %}
                {% if i.avg >= 2 %}
                    ★
                {% else %}
                    ☆
                {% endif %}
                {% if i.avg >= 3 %}
                    ★
                {% else %}
                    ☆
                {% endif %}
                {% if i.avg >= 4 %}
                    ★
                {% else %}
                    ☆
                {% endif %}
                {% if i.avg == 5 %}
                    ★
                {% else %}
                    ☆
                {% endif %}
            </small>
        </div>
    </div>
</div>
{% empty %}
    <h2>Пусто!</h2>
{% endfor %}

frontend/templates/order.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock  %}

{% block header %}

{% include 'header.html' %}

{% endblock %}

{% block override_container %} other-page {% endblock %}

{% block content-base %}

<div class="col-lg-7">
    <h2 class="mt-4">Оформление заказа</h2>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info d-flex justify-content-between align-items-center message-custom-elem"
        style="transition: all 0.4s ease-in-out;" role="dialog">
        {{ message }}
        <span type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </span>
    </div>
    {% endfor %}
    {% endif %}
    <!-- Card -->
    <div class="mb-3">
        <form action="{{ request.path }}" method="POST" id="order-form">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger w-100 pt-2 pb-2">
                Ошибка валидации! <br>
                {{ error }}
            </div>
            {% endfor %}
            <div class="d-flex order-form-group">
                <div class="p-1 order-form-group-field">
                    <label for="{{form.first_name.id_for_label}}">{{form.first_name.label}}</label>
                    {{ form.first_name }}
                    <small>
                        {{ form.username.help_text}}
                    </small>
                    {% for error in form.first_name.errors %}
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="p-1 order-form-group-field">
                    <label for="{{form.last_name.id_for_label}}">{{form.last_name.label}}</label>
                    {{ form.last_name }}
                    <small>
                        {{ form.last_name.help_text}}
                    </small>
                    {% for error in form.last_name.errors %}
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="d-flex order-form-group">
                <div class="p-1 order-form-group-field">
                    <label for="{{form.email.id_for_label}}">{{form.email.label}}</label>
                    {{ form.email }}
                    <small>
                        {{ form.email.help_text}}
                    </small>
                    {% for error in form.email.errors %}
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="p-1 order-form-group-field">
                    <label for="{{form.phone.id_for_label}}">{{form.phone.label}}</label>
                    {{ form.phone }}
                    <small>
                        {{ form.phone.help_text}}
                    </small>
                    {% for error in form.phone.errors %}
                    <p>
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    </p>
                    {% endfor %}
                </div>
            </div>
            {% if conditions %}
            <h5>Условия заказа</h5>
            <ul>
                {% if conditions.delivery %}
                <li>Только самовывоз</li>
                {% else %}
                <li>Доставка</li>
                <li>Самовывоз</li>
                {% endif %}
                {% if conditions.type_buy %}
                <li>Предоплата</li>
                {% else %}
                <li>Наличный расчёт</li>
                <li>Онлайн расчёт</li>
                {% endif %}
            </ul>
            {% endif %}
            {{ form.type_buy_hidden }}
            {{ form.type_delivery_hidden }}
            <script src='https://www.google.com/recaptcha/api.js'></script>
                <div class="form-group g-recaptcha" data-sitekey="6LezzJkbAAAAAP-0SohR8XxBj-5dHFOY90Ni18gX"></div>
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
            <div class="d-flex order-form-group">
                <div class="p-1 order-form-group-field">
                    <label for="{{form.type_buy.id_for_label}}">{{form.type_buy.label}}</label>
                    {{ form.type_buy }}
                    <small>
                        {{ form.type_buy.help_text}}
                    </small>
                    {% for error in form.type_buy.errors %}
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="p-1 order-form-group-field">
                    <label for="{{form.type_delivery.id_for_label}}">{{form.type_delivery.label}}</label>
                    {{ form.type_delivery }}
                    <small>
                        {{ form.type_delivery.help_text}}
                    </small>
                    {% for error in form.type_delivery.errors %}
                    <div class="alert alert-danger w-100 pt-2 pb-2">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                <label for="{{form.address.id_for_label}}">{{form.address.label}}</label>
                {{ form.address }}
                <small>
                    {{ form.address.help_text}}
                </small>
                {% for error in form.address.errors %}
                <div class="alert alert-danger w-100 pt-2 pb-2">
                    {{ error }}
                </div>
                {% endfor %}
            </div>
            <div>
                <label for="{{form.comment.id_for_label}}">{{form.comment.label}}</label>
                {{ form.comment }}
                <small>
                    {{ form.comment.help_text}}
                </small>
                {% for error in form.comment.errors %}
                <div class="alert alert-danger w-100 pt-2 pb-2">
                    {{ error }}
                </div>
                {% endfor %}
            </div>
            {{ form.media }}
        </form>
    </div>

</div>

<div class="col-lg-5">

    <!-- Card -->
    <div class="mb-3">
        <div class="pt-4">

            <h5 class="mb-3">Товары</h5>

            <table class="table order-table" style="background-color: white; font-size: 14px;">
                <thead class="thead-primary">
                    <tr>
                        <th scope="col">Продукт</th>
                        <th scope="col">Доставка</th>
                        <th scope="col">Покупка</th>
                        <th scope="col">Цена</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr class="{% if item.total_quantity <= 0%} table-danger {% endif %}">
                        <td scope="row" style="word-wrap: normal">
                            {{ item.product.brand }} 
                            {{ item.product.model }}  
                            (кол-во. {{ item.quantity }}, 
                            в наличии {{ item.total_quantity }})
                        </td>
                        <td>{{ item.product.delivery|yesno:"Да, Нет" }}</td>
                        <td>{{ item.product.get_type_buy_display }}</td>
                        <td>
                            {% if item.discount %}
                            <del>{{ item.price|floatformat:-2 }}</del>&#8381;
                            {{ item.price_discount|floatformat:-2 }}&#8381;
                            {% else %}
                            {{ item.price|floatformat:-2 }}&#8381;
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td>
                            <strong>
                                Итоговая сумма:
                            </strong>
                        </td>
                        <td></td>
                        <td></td>
                        <td>
                            <strong>
                                {{ cart.total_amount|floatformat:-2 }}&#8381;
                            </strong>
                        </td>
                    </tr>
                </tfoot>
            </table>

            <button type="button" class="btn btn-primary mt-3"
                onclick="document.getElementById('order-form').submit();">
                Оформить заказ
            </button>
            
        </div>
    </div>

    <div class="mb-3 d-flex" style="font-size: 12px;">

        <div class="card w-50 m-2">
            <div class="card-header">
                <strong>Безопасность</strong>
            </div>
            <div class="card-body">
                Безопасность платежей гарантируется использованием SSL протокола.
                Данные вашей банковской карты надежно защищены при оплате онлайн.
            </div>
        </div>
        <div class="card w-50 m-2">
            <div class="card-header">
                <strong>Доставка</strong>
            </div>
            <div class="card-body">
                Доставка на следующий день по всему Челябинску.
            </div>
        </div>
    </div>


</div>

{% endblock %}

{% block ovveride_style %}
<style>
    .django-ckeditor-widget {
        width: 100%;
    }
</style>
{% endblock %}